import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 30-ene.-2025 02:23:56 p. m.'
'File path: C:\\Users\\miguel.reyes\\Documents\\Pruebas automatizadas Agendamiento DEMO\\Agendamiento.side'
'Generated by: null'
'----------------------------------------------------'

String baseUrl = "https://agendamiento-frontend-c-demo-fmfqb3apb8egfnb5.eastus2-01.azurewebsites.net"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /login/ingreso |  | "
// Method open is not supported

"setWindowSize | 1296x688 |  | "
// Method setWindowSize is not supported

"click | css=.float-02 > span |  | "
// Method click is not supported

"click | id=inputBaseuserName |  | "
// Method click is not supported

"type | id=inputBaseuserName | MiguelReyesDemo | "
// Method type is not supported

"click | id=inputBasepassword |  | "
// Method click is not supported

"type | id=inputBasepassword | 99081701187Mm. | "
// Method type is not supported

"selectFrame | index=0 |  | "
// Method selectFrame is not supported

"click | css=.recaptcha-checkbox-border |  | "
// Method click is not supported

"selectFrame | relative=parent |  | "
// Method selectFrame is not supported

"click | css=.btn-04 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | css=.mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | linkText=Parametrización |  | "
// Method click is not supported

"click | linkText=Categorías |  | "
// Method click is not supported

"click | css=.btnIcon-01 |  | "
// Method click is not supported

"click | id=inputBasecategoryName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecategoryName | terminoAleatorio | "
// Method type is not supported

"click | id=inputBasedescriptionundefined |  | "
// Method click is not supported

"executeScript | var descAleatorio = [Técnicas de Imagen Estructural, Técnicas de Imagen Funcional, Técnicas de Imagen No Invasivas y Dinámicas]; var descAleatorio = descAleatorio[Math.floor(Math.random() * descAleatorio.length)]; return descAleatorio; | descAleatorio | "
// Method executeScript is not supported

"type | id=inputBasedescriptionundefined | descAleatorio | "
// Method type is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(9) span:nth-child(2) |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'yellow')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'yellow')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | css=.mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | linkText=Parametrización |  | "
// Method click is not supported

"click | linkText=Especialidades |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const items = document.evaluate(     '//div[contains(@id, cdk-overlay)]/div//li',      document,      null,      XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,      null   );    if (items.snapshotLength > 0) {      items.snapshotItem(items.snapshotLength - 1).click();    } else {      throw new Error('No se encontraron elementos <li> en la lista.');    } |  | "
// Method executeScript is not supported

"click | id=inputBasespecialtiesName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiología, Radiología Intervencionista, Medicina Nuclear, Ultrasonografía (Ecografía), Neurorradiología, Cardiorradiología, Radiología Pediátrica, Radiología Oncológica, Radiología Musculoesquelética, Mamografía (Especialidad en Imágenes de Mama)]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasespecialtiesName | terminoAleatorio | "
// Method type is not supported

"click | id=inputBaseiconName |  | "
// Method click is not supported

"click | css=.icon-item:nth-child(43) #Capa_1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const items = document.evaluate(     '//div[contains(@id, cdk-overlay)]/div//li',      document,      null,      XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,      null   );    if (items.snapshotLength > 0) {      items.snapshotItem(items.snapshotLength - 1).click();    } else {      throw new Error('No se encontraron elementos <li> en la lista.');    } |  | "
// Method executeScript is not supported

"click | id=inputBasespecialtiesName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiología, Radiología Intervencionista, Medicina Nuclear, Ultrasonografía (Ecografía), Neurorradiología, Cardiorradiología, Radiología Pediátrica, Radiología Oncológica, Radiología Musculoesquelética, Mamografía (Especialidad en Imágenes de Mama)]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasespecialtiesName | terminoAleatorio | "
// Method type is not supported

"click | id=inputBaseiconName |  | "
// Method click is not supported

"click | id=Trazado_18383 |  | "
// Method click is not supported

"click | css=.contenedor |  | "
// Method click is not supported

"waitForElementPresent | id=inputBasevaluesMin | 5000 | "
Method waitForElementPresent is not found

"executeScript | return document.getElementById('inputBasevaluesMin') !== null && !document.getElementById('inputBasevaluesMin').disabled && !document.getElementById('inputBasevaluesMin').readOnly; |  | "
// Method executeScript is not supported

"waitForElementVisible | id=inputBasevaluesMin | 5000 | "
Method waitForElementVisible is not found

"executeScript | document.getElementById('inputBasevaluesMin').classList.add('ng-touched'); |  | "
// Method executeScript is not supported

"click | id=inputBasevaluesMin |  | "
// Method click is not supported

"type | id=inputBasevaluesMin | 35 | "
// Method type is not supported

"executeScript | document.getElementById('inputBasevaluesMin').dispatchEvent(new Event('input')); |  | "
// Method executeScript is not supported

"executeScript | document.getElementById('inputBasevaluesMin').dispatchEvent(new Event('change')); |  | "
// Method executeScript is not supported

"click | id=inputBasevaluesInter1 |  | "
// Method click is not supported

"type | id=inputBasevaluesInter1 | 53 | "
// Method type is not supported

"click | id=inputBasevaluesInter2 |  | "
// Method click is not supported

"type | id=inputBasevaluesInter2 | 59 | "
// Method type is not supported

"click | id=inputBasevaluesMax |  | "
// Method click is not supported

"type | id=inputBasevaluesMax | 106 | "
// Method type is not supported

"waitForElementPresent | id=inputBasemaximumTime | 5000 | "
Method waitForElementPresent is not found

"executeScript | document.getElementById('inputBasemaximumTime') !== null && !document.getElementById('inputBasemaximumTime').disabled && !document.getElementById('inputBasemaximumTime').readOnly; |  | "
// Method executeScript is not supported

"waitForElementVisible | id=inputBasemaximumTime | 5000 | "
Method waitForElementVisible is not found

"executeScript | document.getElementById('inputBasemaximumTime').classList.add('ng-touched'); |  | "
// Method executeScript is not supported

"click | id=inputBasemaximumTime |  | "
// Method click is not supported

"type | id=inputBasemaximumTime | 5 | "
// Method type is not supported

"executeScript | document.getElementById('inputBasemaximumTime').dispatchEvent(new Event('input')); |  | "
// Method executeScript is not supported

"executeScript | document.getElementById('inputBasemaximumTime').dispatchEvent(new Event('change')); |  | "
// Method executeScript is not supported

"click | id=inputBaseobservationsundefined |  | "
// Method click is not supported

"executeScript | var Observaciones = [Importancia en pacientes de riesgo, Medidas preventivas clave, Limitaciones y desafíos]; var Observaciones = Observaciones[Math.floor(Math.random() * Observaciones.length)]; return Observaciones; | Observaciones | "
// Method executeScript is not supported

"type | id=inputBaseobservationsundefined | Observaciones | "
// Method type is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const items = document.evaluate(     '//div[contains(@id, cdk-overlay)]/div//li',      document,      null,      XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,      null   );    if (items.snapshotLength > 0) {      items.snapshotItem(items.snapshotLength - 1).click();    } else {      throw new Error('No se encontraron elementos <li> en la lista.');    } |  | "
// Method executeScript is not supported

"click | id=inputBasespecialtiesName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiología, Radiología Intervencionista, Medicina Nuclear, Ultrasonografía (Ecografía), Neurorradiología, Cardiorradiología, Radiología Pediátrica, Radiología Oncológica, Radiología Musculoesquelética, Mamografía (Especialidad en Imágenes de Mama)]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasespecialtiesName | terminoAleatorio | "
// Method type is not supported

"click | id=inputBaseiconName |  | "
// Method click is not supported

"click | id=Trazado_19617 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | css=.mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | linkText=Parametrización |  | "
// Method click is not supported

"click | linkText=Características |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list1 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list1) {     const items1 = list1.getElementsByTagName('li');     if (items1.length >= 3) {       const antepenultimo = items1[items1.length - 3];       antepenultimo.click();     } else {       throw new Error('No hay suficientes elementos en el primer listado.');     }   } else {     throw new Error('No se encontró el primer contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(9) span:nth-child(2) |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list1 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list1) {     const items1 = list1.getElementsByTagName('li');     if (items1.length >= 3) {       const antepenultimo = items1[items1.length - 3];       antepenultimo.click();     } else {       throw new Error('No hay suficientes elementos en el primer listado.');     }   } else {     throw new Error('No se encontró el primer contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(9) span:nth-child(2) |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) span |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list1 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list1) {     const items1 = list1.getElementsByTagName('li');     if (items1.length >= 3) {       const antepenultimo = items1[items1.length - 3];       antepenultimo.click();     } else {       throw new Error('No hay suficientes elementos en el primer listado.');     }   } else {     throw new Error('No se encontró el primer contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) > div |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list2 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list2) {     const items2 = list2.getElementsByTagName('li');     if (items2.length >= 2) {       const penultimo = items2[items2.length - 2];       penultimo.click();     } else {       throw new Error('No hay suficientes elementos en el segundo listado.');     }   } else {     throw new Error('No se encontró el segundo contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) > div |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list2 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list2) {     const items2 = list2.getElementsByTagName('li');     if (items2.length >= 2) {       const penultimo = items2[items2.length - 2];       penultimo.click();     } else {       throw new Error('No hay suficientes elementos en el segundo listado.');     }   } else {     throw new Error('No se encontró el segundo contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) span |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list2 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list2) {     const items2 = list2.getElementsByTagName('li');     if (items2.length >= 2) {       const penultimo = items2[items2.length - 2];       penultimo.click();     } else {       throw new Error('No hay suficientes elementos en el segundo listado.');     }   } else {     throw new Error('No se encontró el segundo contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) span |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list3 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list3) {     const items3 = list3.getElementsByTagName('li');     if (items3.length >= 1) {       const ultimo = items3[items3.length - 1];       ultimo.click();     } else {       throw new Error('No hay suficientes elementos en el tercer listado.');     }   } else {     throw new Error('No se encontró el tercer contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) > div |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list3 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list3) {     const items3 = list3.getElementsByTagName('li');     if (items3.length >= 1) {       const ultimo = items3[items3.length - 1];       ultimo.click();     } else {       throw new Error('No hay suficientes elementos en el tercer listado.');     }   } else {     throw new Error('No se encontró el tercer contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) > div |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const list3 = document.evaluate('//div[contains(@id, cdk-overlay)]/div', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list3) {     const items3 = list3.getElementsByTagName('li');     if (items3.length >= 1) {       const ultimo = items3[items3.length - 1];       ultimo.click();     } else {       throw new Error('No hay suficientes elementos en el tercer listado.');     }   } else {     throw new Error('No se encontró el tercer contenedor <div>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Radiografía de tórax, Tomografía computarizada, Resonancia magnética, Ultrasonido abdominal, Mamografía, Angiografía, Densitometría ósea, Ecocardiograma, Gammagrafía ósea, PET scan]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasecharacteristicName | terminoAleatorio | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(9) > a |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | css=.mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | linkText=Parametrización |  | "
// Method click is not supported

"click | linkText=Preparaciones |  | "
// Method click is not supported

"click | css=.btnIcon-01 |  | "
// Method click is not supported

"click | css=#inputBaseidCategory > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]/div | 5000 | "
Method waitForElementVisible is not found

"executeScript | const items = document.evaluate(     '//div[contains(@id, cdk-overlay)]/div//li',      document,      null,      XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,      null   );    if (items.snapshotLength > 0) {      items.snapshotItem(items.snapshotLength - 1).click();    } else {      throw new Error('No se encontraron elementos <li> en la lista.');    } |  | "
// Method executeScript is not supported

"click | css=#inputBaseidSpecialties > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]//ul | 10000 | "
Method waitForElementVisible is not found

"executeScript | const list = document.evaluate('//div[contains(@id, cdk-overlay)]//ul', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list) {     const items = list.getElementsByTagName('li');     if (items.length > 0) {       const randomIndex = Math.floor(Math.random() * items.length);       items[randomIndex].click();     } else {       throw new Error('No se encontraron elementos <li> en la lista.');     }   } else {     throw new Error('No se encontró el contenedor <ul>.');   } |  | "
// Method executeScript is not supported

"click | css=#inputBaseidCharacteristic > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]//ul | 10000 | "
Method waitForElementVisible is not found

"executeScript | const list = document.evaluate('//div[contains(@id, cdk-overlay)]//ul', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list) {     const items = list.getElementsByTagName('li');     if (items.length > 0) {       const randomIndex = Math.floor(Math.random() * items.length);       items[randomIndex].click();     } else {       throw new Error('No se encontraron elementos <li> en la lista.');     }   } else {     throw new Error('No se encontró el contenedor <ul>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBaseobservationsundefined |  | "
// Method click is not supported

"executeScript | var Observaciones = [Interdisciplinariedad y especialización, Personalización según necesidades clínicas, Desafíos en la interpretación]; var Observaciones = Observaciones[Math.floor(Math.random() * Observaciones.length)]; return Observaciones; | Observaciones | "
// Method executeScript is not supported

"type | id=inputBaseobservationsundefined | Observaciones | "
// Method type is not supported

"click | id=inputBasepreconditionsundefined |  | "
// Method click is not supported

"executeScript | var Precondiciones = [Evaluación clínica previa, Historial médico completo, Disponibilidad de equipo y personal capacitado]; var Precondiciones = Precondiciones[Math.floor(Math.random() * Precondiciones.length)]; return Precondiciones; | Precondiciones | "
// Method executeScript is not supported

"type | id=inputBasepreconditionsundefined | Precondiciones | "
// Method type is not supported

"click | css=#mat-tab-label-0-1 .mdc-tab__text-label |  | "
// Method click is not supported

"click | id=inputBaseindicationsundefined |  | "
// Method click is not supported

"executeScript | var Indicaciones = [Sospecha de patologías específicas, Seguimiento de tratamientos, Prevención y detección temprana]; var Indicaciones = Indicaciones[Math.floor(Math.random() * Indicaciones.length)]; return Indicaciones; | Indicaciones | "
// Method executeScript is not supported

"type | id=inputBaseindicationsundefined | Indicaciones | "
// Method type is not supported

"click | css=#mat-tab-label-0-2 .mdc-tab__text-label |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(1) |  | "
// Method click is not supported

"click | id=inputBaserequirementsundefined |  | "
// Method click is not supported

"executeScript | var Requisitos = [Consentimiento informado, Preparación física del paciente, Protocolos de seguridad, Calibración del equipo, Documentación adecuada]; var Requisitos = Requisitos[Math.floor(Math.random() * Requisitos.length)]; return Requisitos; | Requisitos | "
// Method executeScript is not supported

"type | id=inputBaserequirementsundefined | Requisitos | "
// Method type is not supported

"click | css=.requisito:nth-child(1) .contenedor |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(1) > .mat-icon |  | "
// Method click is not supported

"click | css=.requisito:nth-child(2) #inputBaserequirementsundefined |  | "
// Method click is not supported

"executeScript | var Requisitos = [Consentimiento informado, Preparación física del paciente, Protocolos de seguridad, Calibración del equipo, Documentación adecuada]; var Requisitos = Requisitos[Math.floor(Math.random() * Requisitos.length)]; return Requisitos; | Requisitos | "
// Method executeScript is not supported

"type | css=.requisito:nth-child(2) #inputBaserequirementsundefined | Requisitos | "
// Method type is not supported

"click | css=.btnIcon-01:nth-child(1) |  | "
// Method click is not supported

"click | css=.requisito:nth-child(3) #inputBaserequirementsundefined |  | "
// Method click is not supported

"executeScript | var Requisitos = [Consentimiento informado, Preparación física del paciente, Protocolos de seguridad, Calibración del equipo, Documentación adecuada]; var Requisitos = Requisitos[Math.floor(Math.random() * Requisitos.length)]; return Requisitos; | Requisitos | "
// Method executeScript is not supported

"type | css=.requisito:nth-child(3) #inputBaserequirementsundefined | Requisitos | "
// Method type is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.ng-star-inserted:nth-child(9) span:nth-child(2) |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'confirmar')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'confirmar')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'yellow')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'yellow')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported
