import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 30-ene.-2025 02:23:56 p. m.'
'File path: C:\\Users\\miguel.reyes\\Documents\\Pruebas automatizadas Agendamiento DEMO\\Agendamiento.side'
'Generated by: null'
'----------------------------------------------------'

String baseUrl = "https://agendamiento-frontend-c-demo-fmfqb3apb8egfnb5.eastus2-01.azurewebsites.net"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /login/ingreso |  | "
// Method open is not supported

"setWindowSize | 1296x688 |  | "
// Method setWindowSize is not supported

"click | css=.float-02 > span |  | "
// Method click is not supported

"click | id=inputBaseuserName |  | "
// Method click is not supported

"type | id=inputBaseuserName | MiguelReyesDemo | "
// Method type is not supported

"click | id=inputBasepassword |  | "
// Method click is not supported

"type | id=inputBasepassword | 99081701187Mm. | "
// Method type is not supported

"selectFrame | index=0 |  | "
// Method selectFrame is not supported

"click | css=.recaptcha-checkbox-border |  | "
// Method click is not supported

"selectFrame | relative=parent |  | "
// Method selectFrame is not supported

"click | css=.btn-04 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | css=.mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | linkText=Administración |  | "
// Method click is not supported

"click | linkText=Sedes |  | "
// Method click is not supported

"click | css=.btnIcon-01 |  | "
// Method click is not supported

"click | id=inputBaseattentionCenterCode |  | "
// Method click is not supported

"executeScript | return Math.random().toString(36).substring(2, 12).toUpperCase(); | randomCode | "
// Method executeScript is not supported

"type | id=inputBaseattentionCenterCode | randomCode | "
// Method type is not supported

"click | id=inputBaseattentionCenterName |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Hospital Universitario San Ignacio, Fundación Santa Fe de Bogotá, Clínica Universidad de La Sabana, Hospital Militar Central, Clínica Colsubsidio Calle 100]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBaseattentionCenterName | terminoAleatorio | "
// Method type is not supported

"click | css=#inputBaseidCountry > .contieneSelect > div |  | "
// Method click is not supported

"click | css=.itemSelect > .inputBase |  | "
// Method click is not supported

"type | css=.itemSelect > .inputBase | 170 | "
// Method type is not supported

"click | css=.contieneItems > .itemSelect |  | "
// Method click is not supported

"click | css=#inputBaseidDepartment > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]//ul | 10000 | "
Method waitForElementVisible is not found

"executeScript | const list = document.evaluate('//div[contains(@id, cdk-overlay)]//ul', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list) {     const items = list.getElementsByTagName('li');     if (items.length > 0) {       const randomIndex = Math.floor(Math.random() * items.length);       items[randomIndex].click();     } else {       throw new Error('No se encontraron elementos <li> en la lista.');     }   } else {     throw new Error('No se encontró el contenedor <ul>.');   } |  | "
// Method executeScript is not supported

"click | css=#inputBaseidCity > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]//ul | 10000 | "
Method waitForElementVisible is not found

"executeScript | const list = document.evaluate('//div[contains(@id, cdk-overlay)]//ul', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list) {     const items = list.getElementsByTagName('li');     if (items.length > 0) {       const randomIndex = Math.floor(Math.random() * items.length);       items[randomIndex].click();     } else {       throw new Error('No se encontraron elementos <li> en la lista.');     }   } else {     throw new Error('No se encontró el contenedor <ul>.');   } |  | "
// Method executeScript is not supported

"click | id=inputBasetelephoneNumber |  | "
// Method click is not supported

"executeScript | return '3' + Math.floor(Math.random() * 900000000 + 100000000).toString(); | phoneNumber | "
// Method executeScript is not supported

"type | id=inputBasetelephoneNumber | phoneNumber | "
// Method type is not supported

"click | id=inputBaseaddress |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Calle 123 # 45 - 67, Carrera 56 # 78 - 90,  Avenida 12 # 34 - 56, Diagonal 78 # 12 - 34]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBaseaddress | terminoAleatorio | "
// Method type is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | //*[@id=paginador]/pagination-template/nav/ul/li[last()-1]/a |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td[5]//div[contains(@class, 'contenedor')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td[5]//div[contains(@class, 'contenedor')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td[5]//div[contains(@class, 'contenedor')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td[5]//div[contains(@class, 'contenedor')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'editar')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'editar')] |  | "
// Method click is not supported

"click | css=#inputBaseidDepartment > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]//ul | 10000 | "
Method waitForElementVisible is not found

"executeScript | const list = document.evaluate('//div[contains(@id, cdk-overlay)]//ul', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list) {     const items = list.getElementsByTagName('li');     if (items.length > 0) {       const randomIndex = Math.floor(Math.random() * items.length);       items[randomIndex].click();     } else {       throw new Error('No se encontraron elementos <li> en la lista.');     }   } else {     throw new Error('No se encontró el contenedor <ul>.');   } |  | "
// Method executeScript is not supported

"click | css=#inputBaseidCity > .contieneSelect > div |  | "
// Method click is not supported

"waitForElementVisible | xpath=//div[contains(@id, 'cdk-overlay')]//ul | 10000 | "
Method waitForElementVisible is not found

"executeScript | const list = document.evaluate('//div[contains(@id, cdk-overlay)]//ul', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;   if (list) {     const items = list.getElementsByTagName('li');     if (items.length > 0) {       const randomIndex = Math.floor(Math.random() * items.length);       items[randomIndex].click();     } else {       throw new Error('No se encontraron elementos <li> en la lista.');     }   } else {     throw new Error('No se encontró el contenedor <ul>.');   } |  | "
// Method executeScript is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | //*[@id=paginador]/pagination-template/nav/ul/li[last()-1]/a |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'editar')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'editar')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'eliminar')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'eliminar')] |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"pause | 5000 |  | "
Thread.sleep("5000")
