import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 30-ene.-2025 02:23:56 p. m.'
'File path: C:\\Users\\miguel.reyes\\Documents\\Pruebas automatizadas Agendamiento DEMO\\Agendamiento.side'
'Generated by: null'
'----------------------------------------------------'

String baseUrl = "https://agendamiento-frontend-c-demo-fmfqb3apb8egfnb5.eastus2-01.azurewebsites.net"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /login/ingreso |  | "
// Method open is not supported

"setWindowSize | 1296x688 |  | "
// Method setWindowSize is not supported

"click | css=.float-02 > span |  | "
// Method click is not supported

"click | id=inputBaseuserName |  | "
// Method click is not supported

"type | id=inputBaseuserName | MiguelReyesDemo | "
// Method type is not supported

"click | id=inputBasepassword |  | "
// Method click is not supported

"type | id=inputBasepassword | 99081701187Mm. | "
// Method type is not supported

"selectFrame | index=0 |  | "
// Method selectFrame is not supported

"click | css=.recaptcha-checkbox-border |  | "
// Method click is not supported

"selectFrame | relative=parent |  | "
// Method selectFrame is not supported

"click | css=.btn-04 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | css=.mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | linkText=Administración |  | "
// Method click is not supported

"click | linkText=Procedencias y entidades |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) |  | "
// Method click is not supported

"click | id=inputBaseprocedencia |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [IPS, EPS, ARS, ESE, Entidades de Vigilancia y Control]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBaseprocedencia | terminoAleatorio | "
// Method type is not supported

"click | id=inputBaseentidad |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Fundación Santa Fe de Bogotá, Sanitas, Asmet Salud EPS, Hospital Pablo Tobón Uribe, Invima]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBaseentidad | terminoAleatorio | "
// Method type is not supported

"click | id=inputBasedescripcionundefined |  | "
// Method click is not supported

"executeScript | var terminosMedicos = [Estas entidades garantizan el funcionamiento y la calidad del sistema de salud., Supervisan el uso adecuado de los recursos públicos., Establecen normas y protocolos para la atención en salud., Vigilan el cumplimiento de los derechos de los usuarios., Vigilan el cumplimiento de los derechos de los usuarios.]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | "
// Method executeScript is not supported

"type | id=inputBasedescripcionundefined | terminoAleatorio | "
// Method type is not supported

"click | css=.documento:nth-child(1) > .toggle-btn:nth-child(1) .contenedor |  | "
// Method click is not supported

"click | css=.documento:nth-child(1) > .toggle-btn:nth-child(2) .contenedor |  | "
// Method click is not supported

"waitForElementPresent | id=inputBasevencimientoAutorizacion | 5000 | "
Method waitForElementPresent is not found

"executeScript | return document.getElementById('inputBasevencimientoAutorizacion') !== null && !document.getElementById('inputBasevencimientoAutorizacion').disabled && !document.getElementById('inputBasevencimientoAutorizacion').readOnly; |  | "
// Method executeScript is not supported

"waitForElementVisible | id=inputBasevencimientoAutorizacion | 5000 | "
Method waitForElementVisible is not found

"executeScript | document.getElementById('inputBasevencimientoAutorizacion').classList.add('ng-touched'); |  | "
// Method executeScript is not supported

"click | id=inputBasevencimientoAutorizacion |  | "
// Method click is not supported

"type | id=inputBasevencimientoAutorizacion | 12 | "
// Method type is not supported

"executeScript | document.getElementById('inputBasevencimientoAutorizacion').dispatchEvent(new Event('input')); |  | "
// Method executeScript is not supported

"executeScript | document.getElementById('inputBasevencimientoAutorizacion').dispatchEvent(new Event('change')); |  | "
// Method executeScript is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(7) > a |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'yellow')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'yellow')] |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td[4]//div[contains(@class, 'contenedor')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td[4]//div[contains(@class, 'contenedor')] |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'editar')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'editar')] |  | "
// Method click is not supported

"click | css=.documento:nth-child(2) > .toggle-btn:nth-child(2) .mover |  | "
// Method click is not supported

"waitForElementPresent | id=inputBasevencimientoOrden | 5000 | "
Method waitForElementPresent is not found

"executeScript | return document.getElementById('inputBasevencimientoOrden') !== null && !document.getElementById('inputBasevencimientoOrden').disabled && !document.getElementById('inputBasevencimientoOrden').readOnly; |  | "
// Method executeScript is not supported

"waitForElementVisible | id=inputBasevencimientoOrden | 5000 | "
Method waitForElementVisible is not found

"executeScript | document.getElementById('inputBasevencimientoOrden').classList.add('ng-touched'); |  | "
// Method executeScript is not supported

"click | id=inputBasevencimientoOrden |  | "
// Method click is not supported

"type | id=inputBasevencimientoOrden | 10 | "
// Method type is not supported

"executeScript | document.getElementById('inputBasevencimientoOrden').dispatchEvent(new Event('input')); |  | "
// Method executeScript is not supported

"executeScript | document.getElementById('inputBasevencimientoOrden').dispatchEvent(new Event('change')); |  | "
// Method executeScript is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(7) span:nth-child(2) |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td[4]//div[contains(@class, 'contenedor')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td[4]//div[contains(@class, 'contenedor')] |  | "
// Method click is not supported

"waitForElementVisible | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'eliminar')] | 5000 | "
Method waitForElementVisible is not found

"click | xpath=//table[@class='myTable']//tr[last()]//td//div[contains(@class, 'iconContainer')]//mat-icon[contains(@class, 'eliminar')] |  | "
// Method click is not supported

"pause | 7000 |  | "
Thread.sleep("7000")
