<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_recaptcha</name>
   <tag></tag>
   <elementGuidId>555bb265-8db1-4bc1-80aa-5de0597606ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>35341d0a-f39e-4fb2-9bd4-39d52ab7fe53</webElementGuid>
   </webElementProperties>
</WebElementEntity>
