<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_usuario</name>
   <tag></tag>
   <elementGuidId>a0024710-de8f-4cbd-80cd-e772c397bb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#inputBaseuserName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#inputBaseuserName</value>
      <webElementGuid>11f4c9bb-3cd6-4a4d-87fe-c615f5c4a655</webElementGuid>
   </webElementProperties>
</WebElementEntity>
