<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>2e8ff829-8aea-4ddb-93df-0ec0058379f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#inputBasepassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#inputBasepassword</value>
      <webElementGuid>b17be2a8-9c78-4ec0-9a34-c13680af21aa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
