<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Indicaciones</name>
   <tag></tag>
   <elementGuidId>606f083a-7f89-44fd-a007-fdec5274a7ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#mat-tab-label-0-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#mat-tab-label-0-1</value>
      <webElementGuid>8028462b-44ee-44c6-b28b-822b2b8a4b20</webElementGuid>
   </webElementProperties>
</WebElementEntity>
