import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 30-ene.-2025 02:23:56 p. m.'
'File path: C:\\Users\\miguel.reyes\\Documents\\Pruebas automatizadas Agendamiento DEMO\\Agendamiento.side'
'Generated by: null'
'----------------------------------------------------'

String baseUrl = "https://agendamiento-frontend-c-demo-fmfqb3apb8egfnb5.eastus2-01.azurewebsites.net"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /login/ingreso |  | "
// Method open is not supported

"setWindowSize | 1296x688 |  | "
// Method setWindowSize is not supported

"click | css=.float-02 > span |  | "
// Method click is not supported

"click | id=inputBaseuserName |  | "
// Method click is not supported

"type | id=inputBaseuserName | MiguelReyesDemo | "
// Method type is not supported

"click | id=inputBasepassword |  | "
// Method click is not supported

"click | css=.paddingInputBase:nth-child(4) > .mat-icon |  | "
// Method click is not supported

"click | id=inputBasepassword |  | "
// Method click is not supported

"type | id=inputBasepassword | 99081701187Mm. | "
// Method type is not supported

"selectFrame | index=0 |  | "
// Method selectFrame is not supported

"click | css=.recaptcha-checkbox-border |  | "
// Method click is not supported

"selectFrame | relative=parent |  | "
// Method selectFrame is not supported

"click | css=.btn-04 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | id=Trazado_18455 |  | "
// Method click is not supported

"click | css=.menu-item-with-submenu:nth-child(5) span |  | "
// Method click is not supported

"click | linkText=Categorías |  | "
// Method click is not supported

"click | css=.btnIcon-01 span |  | "
// Method click is not supported

"click | id=inputBasecategoryName |  | "
// Method click is not supported

"type | id=inputBasecategoryName | No elemento | "
// Method type is not supported

"click | id=inputBasedescriptionundefined |  | "
// Method click is not supported

"type | id=inputBasedescriptionundefined | Descripcion | "
// Method type is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(9) span:nth-child(2) |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | id=Trazado_18456 |  | "
// Method click is not supported

"mouseOver | id=Trazado_18456 |  | "
// Method mouseOver is not supported

"mouseOut | id=Trazado_18456 |  | "
// Method mouseOut is not supported

"click | css=.menu-item-with-submenu:nth-child(5) span |  | "
// Method click is not supported

"click | linkText=Especialidades |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) > .mat-icon |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"runScript | window.scrollTo(0,0) |  | "
// Method runScript is not supported

"runScript | window.scrollTo(0,0) |  | "
// Method runScript is not supported

"click | css=.itemSelect:nth-child(22) > .mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | id=inputBasespecialtiesName |  | "
// Method click is not supported

"type | id=inputBasespecialtiesName | No elemento No nefro | "
// Method type is not supported

"click | id=inputBaseiconName |  | "
// Method click is not supported

"click | css=.icon-item:nth-child(18) #Capa_1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=li:nth-child(9) span:nth-child(2) |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | id=Capa_1 |  | "
// Method click is not supported

"click | css=.menu-item-with-submenu:nth-child(5) span |  | "
// Method click is not supported

"click | linkText=Características |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(4) span |  | "
// Method click is not supported

"click | css=.contieneSelect > div |  | "
// Method click is not supported

"runScript | window.scrollTo(0,0) |  | "
// Method runScript is not supported

"click | css=.itemSelect:nth-child(23) > .mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | id=inputBasecharacteristicName |  | "
// Method click is not supported

"type | id=inputBasecharacteristicName | No elemento No nefro | "
// Method type is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"mouseOver | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOver is not supported

"mouseOut | css=.mat-mdc-tooltip-trigger |  | "
// Method mouseOut is not supported

"click | id=Capa_1 |  | "
// Method click is not supported

"mouseOver | id=Capa_1 |  | "
// Method mouseOver is not supported

"mouseOut | id=Capa_1 |  | "
// Method mouseOut is not supported

"click | css=.menu-item-with-submenu:nth-child(5) span |  | "
// Method click is not supported

"click | linkText=Preparaciones |  | "
// Method click is not supported

"click | css=.btnIcon-01 > div |  | "
// Method click is not supported

"click | css=#inputBaseidCategory > .contieneSelect > div |  | "
// Method click is not supported

"runScript | window.scrollTo(0,0) |  | "
// Method runScript is not supported

"runScript | window.scrollTo(0,0) |  | "
// Method runScript is not supported

"click | css=.itemSelect:nth-child(21) > .mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | css=#inputBaseidSpecialties > .contieneSelect > div |  | "
// Method click is not supported

"click | css=.itemSelect > .mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | css=#inputBaseidCharacteristic > .contieneSelect > div |  | "
// Method click is not supported

"click | css=.contiene-opciones |  | "
// Method click is not supported

"click | css=.itemSelect > .mat-mdc-tooltip-trigger |  | "
// Method click is not supported

"click | css=.full-width1 > .shadow |  | "
// Method click is not supported

"click | id=inputBaseobservationsundefined |  | "
// Method click is not supported

"type | id=inputBaseobservationsundefined | Observaciones | "
// Method type is not supported

"click | css=#mat-tab-label-0-0 .mdc-tab__text-label |  | "
// Method click is not supported

"click | id=inputBasepreconditionsundefined |  | "
// Method click is not supported

"type | id=inputBasepreconditionsundefined | Precondiciones | "
// Method type is not supported

"click | css=#mat-tab-label-0-1 .mdc-tab__text-label |  | "
// Method click is not supported

"click | id=inputBaseindicationsundefined |  | "
// Method click is not supported

"type | id=inputBaseindicationsundefined | Indicaciones | "
// Method type is not supported

"click | css=#mat-tab-label-0-2 .mdc-tab__text-label |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(1) > .mat-icon |  | "
// Method click is not supported

"mouseOver | css=.btnIcon-01:nth-child(1) > .mat-icon |  | "
// Method mouseOver is not supported

"mouseOut | css=.btnIcon-01:nth-child(1) > .mat-icon |  | "
// Method mouseOut is not supported

"click | id=inputBaserequirementsundefined |  | "
// Method click is not supported

"type | id=inputBaserequirementsundefined | Esencial | "
// Method type is not supported

"click | css=.mover |  | "
// Method click is not supported

"click | css=.btnIcon-01:nth-child(1) > .mat-icon |  | "
// Method click is not supported

"click | css=.ng-untouched #inputBaserequirementsundefined |  | "
// Method click is not supported

"type | css=.ng-untouched #inputBaserequirementsundefined | Esencial | "
// Method type is not supported

"click | css=.fondoOk |  | "
// Method click is not supported

"click | css=.btn-02 |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.ng-star-inserted:nth-child(9) > .ng-star-inserted |  | "
// Method click is not supported

"click | css=.shadow:nth-child(2) .confirmar |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.shadow:nth-child(2) .yellow |  | "
// Method click is not supported

"click | css=.btn-01 |  | "
// Method click is not supported

"click | css=.icon-button:nth-child(2) #Capa_1 |  | "
// Method click is not supported

"mouseOver | id=Trazado_18545 |  | "
// Method mouseOver is not supported

"click | css=.right-icon1 |  | "
// Method click is not supported

"click | css=.right-icon2 |  | "
// Method click is not supported
