<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemSelect</name>
   <tag></tag>
   <elementGuidId>1b26107e-4b98-4a94-bf0a-e9064d34f743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.itemSelect:nth-child(13)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.itemSelect:nth-child(13)</value>
      <webElementGuid>b1a6b986-5f86-48f9-a66e-584666c16e15</webElementGuid>
   </webElementProperties>
</WebElementEntity>
