import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import internal.GlobalVariable as GlobalVariable
import org.openqa.selenium.Keys as Keys
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject

'----------------------------------------------------'

'This test case script is generated by Katalon Studio'

'Generated date: 30-ene.-2025 02:23:56 p. m.'

'File path: C:\\Users\\miguel.reyes\\Documents\\Pruebas automatizadas Agendamiento DEMO\\Agendamiento.side'

'Generated by: null'

// Abrir navegador y maximizar
'----------------------------------------------------'
WebUI.openBrowser('')

WebUI.maximizeWindow()

// Paso 1: Navegar a la URL de login
WebUI.navigateToUrl('https://agendamiento-frontend-c-demo-fmfqb3apb8egfnb5.eastus2-01.azurewebsites.net/login/ingreso')

// Esperar a que el botón de inicio de sesión esté presente y visible
WebUI.waitForElementPresent(findTestObject('Login/btnLogin'), 10)

WebUI.waitForElementVisible(findTestObject('Login/btnLogin'), 10)

// Hacer clic en el botón de inicio de sesión
WebUI.click(findTestObject('Login/btnLogin'))

// Ingresar el nombre de usuario
WebUI.setText(findTestObject('Login/input_usuario'), 'MiguelReyesDemo')

// Ingresar la contraseña
WebUI.setText(findTestObject('Login/input_password'), '99081701187Mm.')

// Hacer clic en el reCAPTCHA
WebUI.switchToFrame(findTestObject('Login/iframe_recaptcha'), 0)

WebUI.click(findTestObject('Login/checkbox_recaptcha'))

WebUI.switchToDefaultContent()

// Pausar 30 segundos para que el tester pueda resolver el reCAPTCHA
WebUI.delay(30)

// Hacer clic en el botón de login
WebUI.click(findTestObject('Login/btn_login'))

// Interacciones con el menú
WebUI.mouseOver(findTestObject('Roles y Permisos/Menu'))

WebUI.mouseOver(findTestObject('Roles y Permisos/Menu'))

// Hacer clic en el icono de configuración
WebUI.click(findTestObject('Roles y Permisos/Menu'))

// Interacciones con el submenú
WebUI.mouseOver(findTestObject('Roles y Permisos/Menu'))

WebUI.mouseOver(findTestObject('Roles y Permisos/Menu'))

WebUI.mouseOver(findTestObject('Roles y Permisos/Menu'))

// Navegar a la sección de Administracion
WebUI.click(findTestObject('Roles y Permisos/Administracion'))

// Navegar a la sección de Roles y permisos
WebUI.click(findTestObject('Roles y Permisos/Roles y Permisos'))

// Click agregar
WebUI.click(findTestObject('Roles y Permisos/Agregar'))

// Click inputBaseroleName
WebUI.click(findTestObject('Roles y Permisos/inputBaseroleName'))

// Generar un termino aleatorio
def roles = ['Administrador del Sistema', 'Médico', 'Recepcionista', 'Auditor Médico', 'Rol de Invitado']

// Seleccionar un término aleatorio
Random random = new Random()

def terminoAleatorio = roles[random.nextInt(roles.size())]

// Escribir el término aleatorio en el campo de texto con el ID 'inputBaseelementName'
WebUI.setText(findTestObject('Elementos/inputBaseelementName'), terminoAleatorio)

//Elegir condicion especial aleatorio
WebUI.click(findTestObject('Elementos/inputBaseidSpecialCondition'))

WebUI.waitForElementVisible(findTestObject('Elementos/cdkOverlayDiv'), 10)

String script = '\nconst overlayDiv = document.evaluate(\'//div[contains(@id, "cdk-overlay")]//ul\', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;\nif (overlayDiv) {\n    const items = overlayDiv.getElementsByTagName(\'li\');\n    if (items.length > 0) {\n        const randomIndex = Math.floor(Math.random() * items.length);\n        items[randomIndex].click();\n    } else {\n        throw new Error(\'No se encontraron elementos <li> en la lista.\');\n    }\n} else {\n    throw new Error(\'No se encontró el contenedor de la lista desplegable.\');\n}\n'

WebUI.executeJavaScript(script, null)

// Hacer clic en guardar
WebUI.click(findTestObject('Roles y Permisos/Guardar'))

// Hacer clic en aceptar
WebUI.click(findTestObject('Roles y Permisos/Aceptar'))

// Click Ultima Pagina
WebUI.click(findTestObject('Roles y Permisos/Ultima_Page'))

// Click Permisos
WebUI.waitForElementVisible(findTestObject('Roles y Permisos/Permisos'), 10)

WebUI.waitForElementPresent(findTestObject('Roles y Permisos/Permisos'), 10)

WebUI.click(findTestObject('Roles y Permisos/Permisos'))

// Click en permisos de agenda general
WebUI.click(findTestObject('Roles y Permisos/Permisos Agenda General'))

// Method click is not supported
'click | css=.shadow:nth-child(1) .expansor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(1) > td:nth-child(2) .contenedor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(2) > td:nth-child(2) .contenedor |  | '

// Method click is not supported
'click | css=.rotated |  | '

// Method click is not supported
'click | css=.shadow:nth-child(2) .expansor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(2) > td:nth-child(3) .contenedor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(3) > td:nth-child(3) .contenedor |  | '

// Method click is not supported
'click | css=.rotated |  | '

// Method click is not supported
'click | css=.shadow:nth-child(3) .expansor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(3) > td:nth-child(4) .contenedor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(4) > td:nth-child(4) .contenedor |  | '

// Method click is not supported
'click | css=.rotated |  | '

// Method click is not supported
'click | css=.shadow:nth-child(4) .expansor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(4) > td:nth-child(5) .contenedor |  | '

// Method click is not supported
'click | css=.shadow:nth-child(5) > td:nth-child(5) .contenedor |  | '

// Method click is not supported
'click | css=.btn-02 |  | '

// Method click is not supported
'click | //*[@id=paginador]/pagination-template/nav/ul/li[last()-1]/a |  | '

// Method click is not supported
'waitForElementVisible | xpath=//table[@class=\'myTable\']//tr[last()]//td[4]//div[contains(@class, \'contenedor\')] | 5000 | '
Method(waitForElementVisible).is(not).found

'click | xpath=//table[@class=\'myTable\']//tr[last()]//td[4]//div[contains(@class, \'contenedor\')] |  | '

// Method click is not supported
'click | css=.btn-01 |  | '

// Method click is not supported
'waitForElementVisible | xpath=//table[@class=\'myTable\']//tr[last()]//td//div[contains(@class, \'iconContainer\')]//mat-icon[contains(@class, \'editar\')] | 5000 | '
Method(waitForElementVisible).is(not).found

'click | xpath=//table[@class=\'myTable\']//tr[last()]//td//div[contains(@class, \'iconContainer\')]//mat-icon[contains(@class, \'editar\')] |  | '

// Method click is not supported
'click | id=inputBaseroleName |  | '

// Method click is not supported
'executeScript | var terminosMedicos = [Administrador del Sistema, Médico, Recepcionista, Auditor Médico, Rol de Invitado]; var terminoAleatorio = terminosMedicos[Math.floor(Math.random() * terminosMedicos.length)]; return terminoAleatorio; | terminoAleatorio | '

// Method executeScript is not supported
'type | id=inputBaseroleName | terminoAleatorio | '

// Method type is not supported
'click | css=.btn-02 |  | '

// Method click is not supported
'click | css=.btn-01 |  | '

// Method click is not supported
'click | //*[@id=paginador]/pagination-template/nav/ul/li[last()-1]/a |  | '

// Method click is not supported
'waitForElementVisible | xpath=//table[@class=\'myTable\']//tr[last()]//td//div[contains(@class, \'iconContainer\')]//mat-icon[contains(@class, \'editar\')] | 5000 | '
Method(waitForElementVisible).is(not).found

'click | xpath=//table[@class=\'myTable\']//tr[last()]//td//div[contains(@class, \'iconContainer\')]//mat-icon[contains(@class, \'editar\')] |  | '

// Method click is not supported
'click | css=.btn-01 |  | '

// Method click is not supported
'click | //*[@id=paginador]/pagination-template/nav/ul/li[last()-1]/a |  | '

// Method click is not supported
'waitForElementVisible | xpath=//table[@class=\'myTable\']//tr[last()]//td//div[contains(@class, \'iconContainer\')]//mat-icon[contains(@class, \'eliminar\')] | 5000 | '
Method(waitForElementVisible).is(not).found

'click | xpath=//table[@class=\'myTable\']//tr[last()]//td//div[contains(@class, \'iconContainer\')]//mat-icon[contains(@class, \'eliminar\')] |  | '

// Method click is not supported
'click | css=.btn-01 |  | '

// Method click is not supported
'pause | 5000 |  | '
Thread.sleep('5000')

