import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import internal.GlobalVariable as GlobalVariable
import org.openqa.selenium.Keys as Keys
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 30-ene.-2025 02:23:56 p. m.'
'File path: C:\\Users\\miguel.reyes\\Documents\\Pruebas automatizadas Agendamiento DEMO\\Agendamiento.side'
'Generated by: null'
'----------------------------------------------------'

// Abrir navegador y maximizar
WebUI.openBrowser('')

WebUI.maximizeWindow()

// Paso 1: Navegar a la URL de login
WebUI.navigateToUrl('https://agendamiento-frontend-c-demo-fmfqb3apb8egfnb5.eastus2-01.azurewebsites.net/login/ingreso')

// Esperar a que el botón de inicio de sesión esté presente y visible
WebUI.waitForElementPresent(findTestObject('Login/btnLogin'), 10)

WebUI.waitForElementVisible(findTestObject('Login/btnLogin'), 10)

// Hacer clic en el botón de inicio de sesión
WebUI.click(findTestObject('Login/btnLogin'))

// Ingresar el nombre de usuario
WebUI.setText(findTestObject('Login/input_usuario'), 'MiguelReyesDemo')

// Ingresar la contraseña
WebUI.setText(findTestObject('Login/input_password'), '99081701187Mm.')

// Hacer clic en el reCAPTCHA
WebUI.switchToFrame(findTestObject('Login/iframe_recaptcha'), 0)

WebUI.click(findTestObject('Login/checkbox_recaptcha'))

WebUI.switchToDefaultContent()

// Pausar 30 segundos para que el tester pueda resolver el reCAPTCHA
WebUI.delay(30)

// Hacer clic en el botón de login
WebUI.click(findTestObject('Login/btn_login'))

// Interacciones con el menú
WebUI.mouseOver(findTestObject('Categoria/Menu'))

WebUI.mouseOver(findTestObject('Categoria/Menu'))

// Hacer clic en el icono de configuración
WebUI.click(findTestObject('Categoria/Menu'))

// Interacciones con el submenú
WebUI.mouseOver(findTestObject('Categoria/Menu'))

WebUI.mouseOver(findTestObject('Categoria/Menu'))

WebUI.mouseOver(findTestObject('Categoria/Menu'))

// Navegar a la sección de Parametrizacion
WebUI.click(findTestObject('Categoria/Parametrizacion'))

// Navegar a la sección de Categorías
WebUI.click(findTestObject('Categoria/Categorias'))

// Crear nueva categoría
WebUI.click(findTestObject('Categoria/Agregar'))

// Generar datos aleatorios (Groovy)
Random rand = new Random()

def terminosMedicos = ['Radiografía de tórax', 'Tomografía computarizada', 'Resonancia magnética', 'Ultrasonido abdominal'
	, 'Mamografía', 'Angiografía', 'Densitometría ósea', 'Ecocardiograma', 'Gammagrafía ósea', 'PET scan']

def terminoAleatorio = terminosMedicos[rand.nextInt(terminosMedicos.size())]

WebUI.setText(findTestObject('Categoria/Nombre_Categoria'), terminoAleatorio)

def descripciones = ['Técnicas de Imagen Estructural', 'Técnicas de Imagen Funcional', 'Técnicas de Imagen No Invasivas y Dinámicas']

def descAleatoria = descripciones[rand.nextInt(descripciones.size())]

WebUI.setText(findTestObject('Categoria/Descripcion'), descAleatoria)

// Guardar la nueva categoría
WebUI.click(findTestObject('Categoria/Guardar'))

// Click Aceptar
WebUI.click(findTestObject('Categoria/Aceptar'))

// Click Ultima Pagina
WebUI.click(findTestObject('Categoria/Ultima_Page'))

// Ver la descripcion de la última categoría creada
WebUI.waitForElementVisible(findTestObject('Categoria/Check_Descrip'), 10)

WebUI.waitForElementPresent(findTestObject('Categoria/Check_Descrip'), 10)

WebUI.click(findTestObject('Categoria/Check_Descrip'))

WebUI.click(findTestObject('Categoria/Aceptar'))
// Interacciones con el menú
WebUI.mouseOver(findTestObject('Especialidades/Menu'))

WebUI.mouseOver(findTestObject('Especialidades/Menu'))

// Hacer clic en el icono de configuración
WebUI.click(findTestObject('Especialidades/Menu'))

// Interacciones con el submenú
WebUI.mouseOver(findTestObject('Especialidades/Menu'))

WebUI.mouseOver(findTestObject('Especialidades/Menu'))

WebUI.mouseOver(findTestObject('Especialidades/Menu'))

// Navegar a la sección de Parametrizacion
WebUI.click(findTestObject('Especialidades/Parametrizacion'))

// Navegar a la sección de especialidad
WebUI.click(findTestObject('Especialidades/Especialidad'))

// Crear nueva especialidad
WebUI.click(findTestObject('Especialidades/Agregar'))

// Hacer clic en el elemento con el selector CSS (.contieneSelect > div)
WebUI.click(findTestObject('Especialidades/divContieneSelect'))

// Esperar a que el elemento con el XPath (//div[contains(@id, 'cdk-overlay')]/div) sea visible
WebUI.waitForElementVisible(findTestObject('Especialidades/divCdkOverlay'), 5)

// Ejecutar un script JavaScript para hacer clic en el último elemento de la lista
String script = '\n    const items = document.evaluate(\n        \'//div[contains(@id, "cdk-overlay")]/div//li\',\n        document,\n        null,\n        XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,\n        null\n    );\n    if (items.snapshotLength > 0) {\n        items.snapshotItem(items.snapshotLength - 1).click();\n    } else {\n        throw new Error(\'No se encontraron elementos <li> en la lista.\');\n    }\n'

WebUI.executeJavaScript(script, null)

// Hacer clic en el elemento con el ID 'inputBasespecialtiesName'
WebUI.click(findTestObject('Especialidades/inputBasespecialtiesName'))

// Generar un término médico aleatorio
def terminosMedicos2 = ['Radiología', 'Radiología Intervencionista', 'Medicina Nuclear', 'Ultrasonografía (Ecografía)', 'Neurorradiología'
	, 'Cardiorradiología', 'Radiología Pediátrica', 'Radiología Oncológica', 'Radiología Musculoesquelética', 'Mamografía (Especialidad en Imágenes de Mama)']

// Seleccionar un término aleatorio
Random random2 = new Random()

def terminoAleatorio2 = terminosMedicos2[random2.nextInt(terminosMedicos2.size())]

// Escribir el término aleatorio en el campo de texto con el ID 'inputBasespecialtiesName'
WebUI.setText(findTestObject('Especialidades/inputBasespecialtiesName'), terminoAleatorio2)

// Hacer clic en el elemento con el ID 'inputBaseiconName'
WebUI.click(findTestObject('Especialidades/inputBaseiconName'))

// Hacer clic en el icono
WebUI.click(findTestObject('Especialidades/Icono'))
// Click check nefro
WebUI.click(findTestObject('Especialidades/Check_Nefro'))

// Espera a que el elemento esté presente en la página
WebUI.waitForElementPresent(findTestObject('Especialidades/inputBasevaluesMin'), 5)

// Verifica si el elemento está habilitado y no es de solo lectura
def isElementEnabledAndEditable = WebUI.executeJavaScript('return document.getElementById(\'inputBasevaluesMin\') !== null && !document.getElementById(\'inputBasevaluesMin\').disabled && !document.getElementById(\'inputBasevaluesMin\').readOnly;',
	null)

assert isElementEnabledAndEditable == true : 'El elemento no está habilitado o es de solo lectura'

// Espera a que el elemento sea visible
WebUI.waitForElementVisible(findTestObject('Especialidades/inputBasevaluesMin'), 5)

// Añade la clase 'ng-touched' al elemento
WebUI.executeJavaScript('document.getElementById(\'inputBasevaluesMin\').classList.add(\'ng-touched\');', null)

// Click en Valor bloqueante para agendar
WebUI.click(findTestObject('Especialidades/inputBasevaluesMin'))

// Escribe en Valor bloqueante para agendar
WebUI.setText(findTestObject('Especialidades/inputBasevaluesMin'), '35')

// Dispara el evento 'input'
WebUI.executeJavaScript('document.getElementById(\'inputBasevaluesMin\').dispatchEvent(new Event(\'input\'));', null)

// Dispara el evento 'change'
WebUI.executeJavaScript('document.getElementById(\'inputBasevaluesMin\').dispatchEvent(new Event(\'change\'));', null)

// Hacer clic en Valor intermedio para agendar
WebUI.click(findTestObject('Especialidades/inputBasevaluesInter1'))

// Escribir en Valor intermedio para agendar
WebUI.setText(findTestObject('Especialidades/inputBasevaluesInter1'), '53')

// Hacer clic en Valor intermedio para agendar
WebUI.click(findTestObject('Especialidades/inputBasevaluesInter2'))

// Escribir en Valor intermedio para agendar
WebUI.setText(findTestObject('Especialidades/inputBasevaluesInter2'), '59')

// Hacer clic en Valor viable
WebUI.click(findTestObject('Especialidades/inputBasevaluesMax'))

// Escribir en Valor viable
WebUI.setText(findTestObject('Especialidades/inputBasevaluesMax'), '106')

// Espera a que el elemento esté presente en la página
WebUI.waitForElementPresent(findTestObject('Especialidades/inputBasemaximumTime'), 5)

// Verifica si el elemento está habilitado y no es de solo lectura
def isElementEnabledAndEditable2 = WebUI.executeJavaScript('return document.getElementById(\'inputBasemaximumTime\') !== null && !document.getElementById(\'inputBasemaximumTime\').disabled && !document.getElementById(\'inputBasemaximumTime\').readOnly;',
	null)

assert isElementEnabledAndEditable2 == true : 'El elemento no está habilitado o es de solo lectura'

// Espera a que el elemento sea visible
WebUI.waitForElementVisible(findTestObject('Especialidades/inputBasemaximumTime'), 5)

// Añade la clase 'ng-touched' al elemento
WebUI.executeJavaScript('document.getElementById(\'inputBasemaximumTime\').classList.add(\'ng-touched\');', null)

// Hacer clic en Tiempo particular
WebUI.click(findTestObject('Especialidades/inputBasemaximumTime'))

// Escribir en Tiempo particular
WebUI.setText(findTestObject('Especialidades/inputBasemaximumTime'), '5')

// Dispara el evento 'input'
WebUI.executeJavaScript('document.getElementById(\'inputBasemaximumTime\').dispatchEvent(new Event(\'input\'));', null)

// Dispara el evento 'change'
WebUI.executeJavaScript('document.getElementById(\'inputBasemaximumTime\').dispatchEvent(new Event(\'change\'));', null)

// Clic en el campo de observaciones
WebUI.click(findTestObject('Especialidades/inputBaseObservations'))

// Generar una observación aleatoria
def observaciones = ['Enfoque Multidisciplinario', 'Avances Tecnológicos', 'Especialización Creciente']

def observacionSeleccionada = observaciones[new Random().nextInt(observaciones.size())]

// Ingresar la observación en el campo
WebUI.setText(findTestObject('Especialidades/inputBaseObservations'), observacionSeleccionada)

// Click Guardar
WebUI.click(findTestObject('Especialidades/Guardar'))

// Click Aceptar
WebUI.click(findTestObject('Especialidades/Aceptar'))

// Click Ultima Pagina
WebUI.click(findTestObject('Especialidades/Ultima_Page'))

// Interacciones con el menú
WebUI.mouseOver(findTestObject('Caracteristicas/Menu'))

WebUI.mouseOver(findTestObject('Caracteristicas/Menu'))

// Hacer clic en el icono de configuración
WebUI.click(findTestObject('Caracteristicas/Menu'))

// Interacciones con el submenú
WebUI.mouseOver(findTestObject('Caracteristicas/Menu'))

WebUI.mouseOver(findTestObject('Caracteristicas/Menu'))

WebUI.mouseOver(findTestObject('Caracteristicas/Menu'))

// Navegar a la sección de Parametrizacion
WebUI.click(findTestObject('Caracteristicas/Parametrizacion'))

// Navegar a la sección de caracteristicas
WebUI.click(findTestObject('Caracteristicas/Caracteristica'))

// Crear nueva caracteristica
WebUI.click(findTestObject('Caracteristicas/Agregar'))

// Click especialidad
WebUI.click(findTestObject('Caracteristicas/contieneSelect'))

// Selecciona una especialidad
WebUI.click(findTestObject('Caracteristicas/itemSelect_Req'))

// Hacer clic en el elemento con el ID 'inputBasecharacteristicName'
WebUI.click(findTestObject('Caracteristicas/inputBasecharacteristicName'))

// Generar un término médico aleatorio
def terminosMedicos3 = ['Radiografía de tórax', 'Tomografía computarizada', 'Resonancia magnética', 'Ultrasonido abdominal'
	, 'Mamografía', 'Angiografía', 'Densitometría ósea', 'Ecocardiograma', 'Gammagrafía ósea', 'PET scan']

// Seleccionar un término aleatorio
Random random3 = new Random()

def terminoAleatorio3 = terminosMedicos3[random3.nextInt(terminosMedicos3.size())]

// Escribir el término aleatorio en el campo de texto con el ID 'inputBasecharacteristicName'
WebUI.setText(findTestObject('Caracteristicas/inputBasecharacteristicName'), terminoAleatorio3)

// Hacer clic en guardar
WebUI.click(findTestObject('Caracteristicas/Guardar'))

// Hacer clic en aceptar
WebUI.click(findTestObject('Caracteristicas/Aceptar'))

// Click Ultima Pagina
WebUI.click(findTestObject('Caracteristicas/Ultima_Page'))

// Interacciones con el menú
WebUI.mouseOver(findTestObject('Preparaciones/Menu'))

WebUI.mouseOver(findTestObject('Preparaciones/Menu'))

// Hacer clic en el icono de configuración
WebUI.click(findTestObject('Preparaciones/Menu'))

// Interacciones con el submenú
WebUI.mouseOver(findTestObject('Preparaciones/Menu'))

WebUI.mouseOver(findTestObject('Preparaciones/Menu'))

WebUI.mouseOver(findTestObject('Preparaciones/Menu'))

// Navegar a la sección de Parametrizacion
WebUI.click(findTestObject('Preparaciones/Parametrizacion'))

// Navegar a la sección de preparacion
WebUI.click(findTestObject('Preparaciones/Preparaciones'))

// Click Agregar
WebUI.click(findTestObject('Preparaciones/Agregar'))

// Seleccionar categoria
WebUI.click(findTestObject('Preparaciones/Selec_Categoria'))

WebUI.click(findTestObject('Preparaciones/Item_Categoria CE'))

// Seleccionar Especialidad
WebUI.click(findTestObject('Preparaciones/Select_Especialidad'))

WebUI.click(findTestObject('Preparaciones/Item_Especialidad'))

// Seleccionar Caracteristica
WebUI.click(findTestObject('Preparaciones/Selec_Caracteristica'))

WebUI.click(findTestObject('Preparaciones/Item_Caracteristicas'))

// Seleccionar Caracteristica
WebUI.click(findTestObject('Preparaciones/Select_Elementos'))

WebUI.waitForElementPresent(findTestObject('Preparaciones/Item_Elementos'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Item_Elementos'), 10)

WebUI.click(findTestObject('Preparaciones/Item_Elementos'))

// Generar un Observacion aleatorio
def terminosObser1 = ['Interdisciplinariedad y especialización', 'Personalización según necesidades clínicas', 'Desafíos en la interpretación']

// Seleccionar un término aleatorio
Random random6 = new Random()

def terminoAleatorio7 = terminosObser1[random6.nextInt(terminosObser1.size())]

// Escribir el término aleatorio en el campo de texto con el ID 'inputBaseobservationsundefined'
WebUI.setText(findTestObject('Preparaciones/Observaciones'), terminoAleatorio7)

// Generar una precondicion aleatorio
def terminosPreco = ['Evaluación clínica previa', 'Historial médico completo', 'Disponibilidad de equipo y personal capacitado']

// Seleccionar un término aleatorio
Random random7 = new Random()

def terminoAleatorio8 = terminosPreco[random7.nextInt(terminosPreco.size())]

// Escribir el término aleatorio en el campo de texto con el ID 'inputBasepreconditionsundefined'
WebUI.setText(findTestObject('Preparaciones/Precondicion'), terminoAleatorio8)

// Generar una precondicion aleatorio
def terminosIndic = ['Sospecha de patologías específicas', 'Seguimiento de tratamientos', 'Prevención y detección temprana']

// Seleccionar un término aleatorio
Random random8 = new Random()

def terminoAleatorio9 = terminosIndic[random8.nextInt(terminosIndic.size())]

// Click Indicaciones
WebUI.click(findTestObject('Preparaciones/Click_Indicaciones'))

// Escribir el término aleatorio en el campo de texto con el ID 'inputBaseindicationsundefined'
WebUI.setText(findTestObject('Preparaciones/Indicaciones'), terminoAleatorio9)

// Seleccionar Requisitos
WebUI.click(findTestObject('Preparaciones/Requisitos'))

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Añadir_Requisito'))

// Generar un requisito aleatorio
def terminosReq = ['Consentimiento informado', 'Preparación física del paciente', 'Protocolos de seguridad', 'Calibración del equipo'
	, 'Documentación adecuada']

// Seleccionar un término aleatorio
Random random9 = new Random()

def terminoAleatorio10 = terminosReq[random9.nextInt(terminosReq.size())]

// Escribir el término aleatorio en el campo de texto del requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Desc_Requis'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Desc_Requis'), 10)

WebUI.setText(findTestObject('Preparaciones/Desc_Requis'), terminoAleatorio10)

// Check Esencial
WebUI.waitForElementPresent(findTestObject('Preparaciones/Check_Requis'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Check_Requis'), 10)

WebUI.click(findTestObject('Preparaciones/Check_Requis'))

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Añadir_Requisito'))

terminoAleatorio4 = (terminosReq[random4.nextInt(terminosReq.size())])

// Escribir el término aleatorio en el campo de texto del requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Desc_Requis 2'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Desc_Requis 2'), 10)

WebUI.setText(findTestObject('Preparaciones/Desc_Requis 2'), terminoAleatorio4)

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Añadir_Requisito'))

terminoAleatorio4 = (terminosReq[random4.nextInt(terminosReq.size())])

// Escribir el término aleatorio en el campo de texto del requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Des_Requisito 3'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Des_Requisito 3'), 10)

WebUI.setText(findTestObject('Preparaciones/Des_Requisito 3'), terminoAleatorio4)

// Check Esencial
WebUI.waitForElementPresent(findTestObject('Preparaciones/Check_Requis 3'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Check_Requis 3'), 10)

WebUI.click(findTestObject('Preparaciones/Check_Requis 3'))

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Añadir_Requisito'))

terminoAleatorio4 = (terminosReq[random4.nextInt(terminosReq.size())])

// Escribir el término aleatorio en el campo de texto del requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Des_Requisito 4'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Des_Requisito 4'), 10)

WebUI.setText(findTestObject('Preparaciones/Des_Requisito 4'), terminoAleatorio4)

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Añadir_Requisito'))

terminoAleatorio4 = (terminosReq[random4.nextInt(terminosReq.size())])

// Escribir el término aleatorio en el campo de texto del requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Des_Requisito 5'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Des_Requisito 5'), 10)

WebUI.setText(findTestObject('Preparaciones/Des_Requisito 5'), terminoAleatorio4)

// Check Esencial
WebUI.waitForElementPresent(findTestObject('Preparaciones/Check_Requis 5'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Check_Requis 5'), 10)

WebUI.click(findTestObject('Preparaciones/Check_Requis 5'))

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Añadir_Requisito'))

terminoAleatorio4 = (terminosReq[random4.nextInt(terminosReq.size())])

// Escribir el término aleatorio en el campo de texto del requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Des_Requisito 6'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Des_Requisito 6'), 10)

WebUI.setText(findTestObject('Preparaciones/Des_Requisito 6'), terminoAleatorio4)

// click casilla para marcar requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 2'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 2'), 10)

WebUI.click(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 2'))

// click casilla para marcar requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 3'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 3'), 10)

WebUI.click(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 3'))

// click casilla para marcar requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 4'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 4'), 10)

WebUI.click(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 4'))

// click casilla para marcar requisito
WebUI.waitForElementPresent(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 6'), 10)

WebUI.waitForElementVisible(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 6'), 10)

WebUI.click(findTestObject('Preparaciones/Ambiente DEMO/Marca Requisito 6'))

// Sumar requisitos
WebUI.click(findTestObject('Preparaciones/Eliminar_Requisito'))

// Hacer clic en guardar
WebUI.click(findTestObject('Preparaciones/Guardar'))

// Hacer clic en aceptar
WebUI.click(findTestObject('Preparaciones/Aceptar'))

// Click Ultima Pagina
WebUI.click(findTestObject('Preparaciones/Ultima_Page'))

// Ver niveles
WebUI.waitForElementVisible(findTestObject('Preparaciones/Niveles'), 10)

WebUI.waitForElementPresent(findTestObject('Preparaciones/Niveles'), 10)

WebUI.click(findTestObject('Preparaciones/Niveles'))

// Hacer clic en aceptar
WebUI.click(findTestObject('Preparaciones/Aceptar'))

// Ver detalles
WebUI.waitForElementVisible(findTestObject('Preparaciones/Detalles'), 10)

WebUI.waitForElementPresent(findTestObject('Preparaciones/Detalles'), 10)

WebUI.click(findTestObject('Preparaciones/Detalles'))

// Hacer clic en aceptar
WebUI.click(findTestObject('Preparaciones/Aceptar'))

// Cerrar navegador
WebUI.closeBrowser()
