<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nombre_Categoria</name>
   <tag></tag>
   <elementGuidId>91164fbc-71eb-4143-86d8-1d7e6cbd46a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#inputBasecategoryName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#inputBasecategoryName</value>
      <webElementGuid>5006bf02-3fde-4077-bf6a-9d141221af88</webElementGuid>
   </webElementProperties>
</WebElementEntity>
